/**
 * @file game/[roomCode].tsx
 * @description Game screen for memoryEngine. Features:
 *   - Real engine logic (deck, rules, scoring)
 *   - Online sync via Socket.IO /game namespace
 *   - AnimatedCard + haptic feedback
 *   - Player avatars, phase banner, action hints, quit confirm, winner modal
 *
 * Generated by tools/generate-game-screens.js — re-run after editing the
 * script to regenerate, or edit freely if you want game-specific UI.
 */
import React, { useReducer, useEffect, useState, useCallback, useRef } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  Alert,
  Pressable,
  Modal,
  Animated,
  Easing,
} from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { LinearGradient } from 'expo-linear-gradient';
import { Ionicons } from '@expo/vector-icons';
import { useTranslation } from 'react-i18next';
import * as Haptics from 'expo-haptics';
import { io, Socket } from 'socket.io-client';
import AppHeader from '../../src/components/AppHeader';
import AnimatedCard from '../../src/components/AnimatedCard';
import { useTheme } from '../../src/contexts/AppProviders';
import { logger } from '../../src/utils/logger';
import { APP_CONFIG } from '../../src/config/app.config';
import { SOCKET_URL } from '../../shared/api';
import * as Engine from '../../src/game/memoryEngine';

const log = logger.scoped('GameScreen');
const ME = 'p1';
const BOT_THINK_MS = 1200;

// Reusable presentational sub-components  ──────────────────────────────
function PhaseBanner({ phase, current, isMyTurn, winner, palette }: any) {
  const text = winner
    ? `🏆 ${winner.name ?? winner.winnerId ?? 'Fin'}`
    : isMyTurn
      ? '✋ À votre tour'
      : `⏳ ${current?.name ?? 'Bot'} joue…`;
  const bg = winner ? '#10B981' : isMyTurn ? APP_CONFIG.primary : 'rgba(255,255,255,0.1)';
  return (
    <View style={[styles.banner, { backgroundColor: bg, borderColor: palette.border }]}>
      <Text style={styles.bannerText}>{text}</Text>
      {phase && !winner && <Text style={styles.bannerPhase}>Phase : {phase}</Text>}
    </View>
  );
}

function AvatarRow({ players, currentId, palette }: any) {
  return (
    <View style={styles.avatarRow}>
      {players?.map((p: any) => {
        const isActive = p.id === currentId;
        return (
          <View key={p.id} style={[styles.avatarBox, isActive && { borderColor: APP_CONFIG.primary, borderWidth: 2 }]}>
            <View style={[styles.avatar, { backgroundColor: isActive ? APP_CONFIG.primary : APP_CONFIG.secondary }]}>
              <Text style={styles.avatarEmoji}>{p.isBot ? '🤖' : '👤'}</Text>
            </View>
            <Text style={[styles.avatarName, { color: palette.text }]} numberOfLines={1}>
              {p.name}
            </Text>
            <View style={styles.avatarStats}>
              <Text style={[styles.avatarScore, { color: APP_CONFIG.primary }]}>
                {p.score ?? p.chips ?? p.pairs ?? p.pairsCount ?? (p.hand?.length ?? 0)}
              </Text>
              {p.folded && <Text style={styles.avatarFold}>fold</Text>}
            </View>
          </View>
        );
      })}
    </View>
  );
}

function HelpChip({ palette, text }: any) {
  return (
    <View style={[styles.helpChip, { borderColor: palette.border }]}>
      <Ionicons name="information-circle-outline" size={14} color={palette.textSecondary} />
      <Text style={[styles.helpText, { color: palette.textSecondary }]}>{text}</Text>
    </View>
  );
}

function MoveLog({ entries, palette }: any) {
  if (!entries || entries.length === 0) return null;
  return (
    <View style={[styles.log, { borderColor: palette.border }]}>
      <Text style={[styles.logTitle, { color: palette.textSecondary }]}>📜 Derniers coups</Text>
      {entries.slice(-5).reverse().map((e: any, i: number) => (
        <Text key={i} style={[styles.logRow, { color: palette.text }]} numberOfLines={1}>
          {e.icon ?? '•'} <Text style={{ color: palette.textSecondary }}>{e.who}</Text> {e.what}
        </Text>
      ))}
    </View>
  );
}

function FeedbackToast({ message, visible, color }: any) {
  const opacity = useRef(new Animated.Value(0)).current;
  useEffect(() => {
    if (visible) {
      Animated.sequence([
        Animated.timing(opacity, { toValue: 1, duration: 180, useNativeDriver: true }),
        Animated.delay(900),
        Animated.timing(opacity, { toValue: 0, duration: 280, useNativeDriver: true }),
      ]).start();
    }
  }, [visible, message]);
  return (
    <Animated.View pointerEvents="none" style={[styles.toast, { opacity, backgroundColor: color ?? APP_CONFIG.primary }]}>
      <Text style={styles.toastText}>{message}</Text>
    </Animated.View>
  );
}

function WinnerModal({ visible, winner, onQuit, onAgain, palette }: any) {
  return (
    <Modal visible={visible} transparent animationType="fade">
      <View style={styles.modalBackdrop}>
        <LinearGradient colors={['#0A0A1A', APP_CONFIG.secondary]} style={[styles.modalCard, { borderColor: APP_CONFIG.primary }]}>
          <Text style={styles.modalEmoji}>🏆</Text>
          <Text style={styles.modalTitle}>{winner?.name ?? winner?.winnerId ?? 'Bravo !'}</Text>
          <Text style={[styles.modalSub, { color: palette.textSecondary }]}>{APP_CONFIG.name}</Text>
          <View style={{ flexDirection: 'row', gap: 12, marginTop: 20 }}>
            <TouchableOpacity onPress={onAgain} style={[styles.modalBtn, { backgroundColor: APP_CONFIG.primary }]}>
              <Text style={styles.modalBtnText}>🔄 Rejouer</Text>
            </TouchableOpacity>
            <TouchableOpacity onPress={onQuit} style={[styles.modalBtn, { backgroundColor: 'rgba(255,255,255,0.15)' }]}>
              <Text style={styles.modalBtnText}>Quitter</Text>
            </TouchableOpacity>
          </View>
        </LinearGradient>
      </View>
    </Modal>
  );
}

// Shared base styles — extended per game-kind below
const styles = StyleSheet.create({
  banner: {
    padding: 14, borderRadius: 14, alignItems: 'center', borderWidth: 1, marginBottom: 10,
  },
  bannerText: { color: '#fff', fontSize: 15, fontFamily: 'Inter-Bold' },
  bannerPhase: { color: 'rgba(255,255,255,0.85)', fontSize: 11, fontFamily: 'Inter-SemiBold', marginTop: 3 },
  avatarRow: {
    flexDirection: 'row', justifyContent: 'space-around', marginBottom: 12,
    paddingVertical: 10, paddingHorizontal: 6,
    backgroundColor: 'rgba(255,255,255,0.03)', borderRadius: 14,
  },
  avatarBox: { alignItems: 'center', minWidth: 60, padding: 4, borderRadius: 12 },
  avatar: { width: 38, height: 38, borderRadius: 19, alignItems: 'center', justifyContent: 'center' },
  avatarEmoji: { fontSize: 18 },
  avatarName: { fontSize: 11, fontFamily: 'Inter-SemiBold', marginTop: 4, maxWidth: 60 },
  avatarStats: { flexDirection: 'row', alignItems: 'center', gap: 4, marginTop: 2 },
  avatarScore: { fontSize: 13, fontFamily: 'Inter-Black' },
  avatarFold: { fontSize: 9, color: '#EF4444', fontFamily: 'Inter-Bold' },
  helpChip: {
    flexDirection: 'row', alignItems: 'center', gap: 6,
    paddingHorizontal: 10, paddingVertical: 6, borderRadius: 999, borderWidth: 1,
    backgroundColor: 'rgba(255,255,255,0.03)', alignSelf: 'flex-start', marginBottom: 8,
  },
  helpText: { fontSize: 11, fontFamily: 'Inter-Regular', flexShrink: 1 },
  log: { padding: 10, borderRadius: 10, borderWidth: 1, backgroundColor: 'rgba(0,0,0,0.2)', marginTop: 12 },
  logTitle: { fontSize: 11, fontFamily: 'Inter-Bold', letterSpacing: 1, marginBottom: 4 },
  logRow: { fontSize: 12, fontFamily: 'Inter-Regular', paddingVertical: 1 },
  toast: {
    position: 'absolute', top: 100, alignSelf: 'center',
    paddingHorizontal: 22, paddingVertical: 12, borderRadius: 999,
    elevation: 8, shadowColor: '#000', shadowOpacity: 0.4, shadowRadius: 8, zIndex: 100,
  },
  toastText: { color: '#fff', fontSize: 14, fontFamily: 'Inter-Black', letterSpacing: 0.5 },
  modalBackdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,0.85)', alignItems: 'center', justifyContent: 'center' },
  modalCard: {
    padding: 28, borderRadius: 20, alignItems: 'center', borderWidth: 2,
    minWidth: 280, maxWidth: '85%',
  },
  modalEmoji: { fontSize: 56, marginBottom: 8 },
  modalTitle: { color: '#fff', fontSize: 24, fontFamily: 'Inter-Black', letterSpacing: 0.5 },
  modalSub: { fontSize: 13, fontFamily: 'Inter-SemiBold', marginTop: 4 },
  modalBtn: { paddingHorizontal: 22, paddingVertical: 12, borderRadius: 12 },
  modalBtnText: { color: '#fff', fontSize: 14, fontFamily: 'Inter-Bold' },
});

// Hook : online sync via Socket.IO /game (best-effort, doesn't block UI)
function useGameSocket(roomCode: string | undefined, onState: (s: any) => void) {
  const socketRef = useRef<Socket | null>(null);
  const [connected, setConnected] = useState(false);
  useEffect(() => {
    if (!roomCode) return;
    const s = io(`${SOCKET_URL}/game`, { transports: ['websocket'], timeout: 4000 });
    socketRef.current = s;
    s.on('connect', () => {
      setConnected(true);
      log.bin(`socket /game connected → join room:${roomCode}`);
      s.emit('game:join', { roomCode });
    });
    s.on('game:state', (snapshot: any) => {
      log.bout('game:state received', { phase: snapshot?.phase });
      onState(snapshot);
    });
    s.on('disconnect', () => setConnected(false));
    s.on('connect_error', (e: any) => log.warn('socket connect_error', e?.message));
    return () => { s.disconnect(); socketRef.current = null; };
  }, [roomCode]);
  const emitMove = useCallback((action: any) => {
    socketRef.current?.emit('game:action', { roomCode, action });
  }, [roomCode]);
  return { connected, emitMove };
}

const HELP_TEXT = "Retournez 2 cartes par tour. Trouvez toutes les paires.";
const FEEDBACK_CAPTURE = "💎 Paire !";

export default function GameScreen() {
  const { roomCode } = useLocalSearchParams<{ roomCode: string }>();
  const router = useRouter();
  const { t } = useTranslation();
  const { palette } = useTheme();

  const [state, dispatch] = useReducer(Engine.gameReducer as any, undefined, () =>
    (Engine as any).createInitialState(1, 1)  // 1 human, 1 bot
  );

  const [moveLog, setMoveLog] = useState<any[]>([]);
  const [toast, setToast] = useState<any>(null);
  const [showQuit, setShowQuit] = useState(false);
  const grid = state.grid ?? [];
  const current = state.players?.[state.currentPlayerIndex];
  const winner = state.phase === 'gameOver'
    ? (state.winnerId ? state.players?.find((p: any) => p.id === state.winnerId) : { name: 'Égalité' })
    : null;
  const isMyTurn = current?.id === ME && !winner;

  const { connected, emitMove } = useGameSocket(roomCode as any, (snap) => {
    if (snap) dispatch({ type: 'SYNC_FROM_SERVER', state: snap } as any);
  });

  useEffect(() => {
    if (winner) {
      Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success).catch(() => {});
      return;
    }
    if (current?.isBot && (Engine as any).botPlay) {
      const timer = setTimeout(() => {
        const action = (Engine as any).botPlay(state);
        if (action) { dispatch(action); emitMove(action); }
      }, BOT_THINK_MS);
      return () => clearTimeout(timer);
    }
  }, [state, current, winner, emitMove]);

  const flip = (idx: number) => {
    if (!isMyTurn) return;
    const cell = grid[idx];
    if (cell?.faceUp || cell?.matched) return;
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light).catch(() => {});
    const action = { type: 'FLIP_CARD', index: idx } as any;
    dispatch(action); emitMove(action);
    setMoveLog(l => [...l, { icon: '👤', who: 'Vous', what: `a retourné #${idx + 1}` }]);
  };

  // Detect match feedback when 2 cards are face-up & same value
  useEffect(() => {
    const upCards = (state.grid ?? []).filter((c: any) => c.faceUp && !c.matched);
    if (upCards.length === 2 && upCards[0].card?.value === upCards[1].card?.value) {
      setToast({ msg: FEEDBACK_CAPTURE, color: '#10B981', key: Date.now() });
      Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium).catch(() => {});
    }
  }, [state]);

  const restart = () => {
    dispatch({ type: 'RESET', playerCount: 1, botCount: 1 } as any);
    setMoveLog([]);
  };

  return (
    <View style={[localStyles.root, { backgroundColor: palette.bg }]}>
      <LinearGradient colors={palette.bgGradient} style={StyleSheet.absoluteFill} />
      <AppHeader title={APP_CONFIG.name} subtitle={`Salon ${roomCode ?? '—'} ${connected ? '· 🟢' : '· 🔌'}`} showBack onBack={() => setShowQuit(true)} />

      <ScrollView contentContainerStyle={localStyles.body}>
        <AvatarRow players={state.players} currentId={current?.id} palette={palette} />
        <PhaseBanner phase={undefined} current={current} isMyTurn={isMyTurn} winner={winner} palette={palette} />
        <HelpChip palette={palette} text={HELP_TEXT} />

        <Text style={[localStyles.handTitle, { color: palette.text, marginTop: 8 }]}>
          🧠 Grille {(Engine as any).GRID_ROWS ?? 4}×{(Engine as any).GRID_COLS ?? 5}
        </Text>
        <View style={localStyles.grid}>
          {grid.map((cell: any, idx: number) => {
            const visible = cell.faceUp || cell.matched;
            return (
              <Pressable
                key={idx}
                onPress={() => flip(idx)}
                disabled={!isMyTurn || visible}
                style={({ pressed }) => [
                  localStyles.gridCell,
                  {
                    borderColor: cell.matched ? '#10B981' : APP_CONFIG.primary,
                    backgroundColor: cell.matched
                      ? 'rgba(16,185,129,0.18)'
                      : visible
                        ? 'rgba(255,255,255,0.10)'
                        : APP_CONFIG.secondary,
                    transform: [{ scale: pressed ? 0.95 : 1 }],
                  },
                ]}
              >
                {visible ? (
                  <AnimatedCard value={String(cell.card?.value ?? '?')} suit={cell.card?.suit} width={56} height={78} facing="up" />
                ) : (
                  <Text style={localStyles.cellBack}>?</Text>
                )}
              </Pressable>
            );
          })}
        </View>

        <MoveLog entries={moveLog} palette={palette} />
      </ScrollView>

      <FeedbackToast message={toast?.msg} visible={!!toast} color={toast?.color} key={toast?.key} />
      <WinnerModal visible={!!winner} winner={winner} onAgain={restart} onQuit={() => router.back()} palette={palette} />

      <Modal visible={showQuit} transparent animationType="fade">
        <View style={styles.modalBackdrop}>
          <View style={[styles.modalCard, { backgroundColor: palette.card, borderColor: palette.border }]}>
            <Text style={styles.modalTitle}>Quitter la partie ?</Text>
            <View style={{ flexDirection: 'row', gap: 12, marginTop: 18 }}>
              <TouchableOpacity onPress={() => setShowQuit(false)} style={[styles.modalBtn, { backgroundColor: 'rgba(255,255,255,0.15)' }]}><Text style={styles.modalBtnText}>Annuler</Text></TouchableOpacity>
              <TouchableOpacity onPress={() => { setShowQuit(false); router.back(); }} style={[styles.modalBtn, { backgroundColor: '#EF4444' }]}><Text style={styles.modalBtnText}>Quitter</Text></TouchableOpacity>
            </View>
          </View>
        </View>
      </Modal>
    </View>
  );
}

const localStyles = StyleSheet.create({
  root: { flex: 1 },
  body: { padding: 14, paddingBottom: 40 },
  handTitle: { fontSize: 14, fontFamily: 'Inter-Bold', marginBottom: 8 },
  grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, justifyContent: 'center' },
  gridCell: { width: 64, height: 86, borderRadius: 12, borderWidth: 2, alignItems: 'center', justifyContent: 'center' },
  cellBack: { color: '#fff', fontSize: 28, fontFamily: 'Inter-Black' },
});
